# Generated by Django 4.1.7 on 2023-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
